FROM mcr.microsoft.com/dotnet/core/sdk:3.1
WORKDIR /app
RUN mkdir aspnetBuild
 
RUN mkdir aspnetcoffee
 
COPY . .
 
RUN dotnet publish aspnetcoffee/Asp.NetCoffeeTool.csproj.csproj --output /app/aspnetBuild/aspnetcoffee/ --configuration Release
 